import os
from dotenv import load_dotenv
load_dotenv()

AZURE_OPENAI_API_TYPE = os.getenv("AZURE_OPENAI_API_TYPE") 
AZURE_OPENAI_API_BASE = os.getenv("AZURE_OPENAI_API_BASE") 
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY") 
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION") 
AZURE_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_EMBEDDING_DEPLOYMENT")
AZURE_VECTOR_STORE_ADDRESS = os.getenv("AZURE_VECTOR_STORE_ADDRESS")
AZURE_VECTOR_STORE_PWD = os.getenv("AZURE_VECTOR_STORE_PWD")
AZURE_VECTOR_STORE_INDEX_NAME = os.getenv("AZURE_VECTOR_STORE_INDEX_NAME")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
AZURE_OPENAI_API_TYPE = os.getenv("AZURE_OPENAI_API_TYPE")
AZURE_OPENAI_GPT_API_VERSION = os.getenv("AZURE_OPENAI_GPT_API_VERSION")